import { openMemoryDb } from '../src/db/index.js';
import { registerStation, backfillStation } from '../src/engine/backfill.js';
import { buildOutlook } from '../src/engine/outlook.js';
import { report } from '../src/engine/stats.js';
import { getStation } from '../src/engine/store.js';
const db = openMemoryDb();
await registerStation(db, 'KTEB');
await backfillStation(db, 'KTEB', 60);
const st = getStation(db, 'KTEB')!;
let t0 = Date.now();
const rep = report(db, 'KTEB', 60);
console.log('report ms', Date.now() - t0);
console.log(JSON.stringify({ pairs: rep.pairs, op: rep.operativePairs, opErrors: rep.operative.errors, ifr: rep.operative.ifr, byLead: rep.byLead.map(b => ({ lead: b.lead, n: b.n, hit: b.errors.category.hitRate, pod: b.ifr.pod, far: b.ifr.far })), wx: rep.operative.wx, amendments: rep.amendments, nws: rep.nws.map(n => ({ d: n.leadDay, n: n.n, t: n.temp, hit: n.category.hitRate })), models: rep.models.map(m => ({ m: m.model, ld: m.leadDays, n: m.n, t: m.temp, hit: m.category.hitRate, pod: m.category.ifrPod })), busts: rep.busts.slice(0, 3) }, null, 1).slice(0, 6000));
t0 = Date.now();
const o = buildOutlook(db, st, 120, 60);
console.log('outlook ms', Date.now() - t0);
console.log(JSON.stringify({ sources: o.sources, trends: o.trends, insights: o.insights, days: o.days.map(d => d.summary), skill: o.skill }, null, 1).slice(0, 8000));
console.log(JSON.stringify(o.hours[0], null, 1).slice(0, 4000));
console.log(JSON.stringify(o.hours[40], null, 1).slice(0, 3000));
